<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Bella Baxter URL
    |--------------------------------------------------------------------------
    | Base URL of the Baxter API. Defaults to BELLA_BAXTER_URL env var.
    */
    'url' => env('BELLA_BAXTER_URL', 'https://api.bella-baxter.io'),

    /*
    |--------------------------------------------------------------------------
    | API Key
    |--------------------------------------------------------------------------
    | The API key (client_id:client_secret) for authenticating with Bella Baxter.
    | Generate with: bella apikeys create
    */
    'api_key' => env('BELLA_BAXTER_API_KEY', ''),

    /*
    |--------------------------------------------------------------------------
    | Auto-load secrets at boot
    |--------------------------------------------------------------------------
    | When true, BellaServiceProvider automatically fetches all secrets at
    | application boot and injects them into the PHP environment ($_ENV + putenv).
    | Set to false if you prefer to call Bella::getAllSecrets() manually.
    */
    'auto_load' => env('BELLA_BAXTER_AUTO_LOAD', true),
    /*
    |--------------------------------------------------------------------------
    | ZKE Private Key
    |--------------------------------------------------------------------------
    | PKCS#8 (or SEC1) PEM private key for Zero-Knowledge Encryption transport.
    | Generated by `bella auth setup`. When set, the SDK uses your persistent
    | device key instead of an ephemeral key, enabling server-side DEK wrapping.
    | Leave empty to use standard ephemeral E2EE (default).
    */
    'private_key' => env('BELLA_BAXTER_PRIVATE_KEY'),
];
